dist: trusty
language: java
jdk:
  - oraclejdk8
branches:
  only:
    - master
before_install:
  - chmod +x gradlew
script:
  - ./gradlew war
  - ls ./build/libs
  - git clone -b https://$GH_TOKEN/yindaheng98/yindaheng98.top.git
  - cp -rf ./build/libs/* ./yindaheng98.top/apps/jetty/
  - ls ./yindaheng98.top/apps/jetty/
