dist: trusty
language: java
jdk:
  - oraclejdk8
branches:
  only:
    - master
before_install:
  - chmod +x gradlew
script:
  - ./gradlew war
  - ls ./build/libs
  - git clone https://$GH_TOKEN@github.com/yindaheng98/yindaheng98.top.git
  - cp -rf ./build/libs/* ./yindaheng98.top/apps/jetty/
  - ls ./yindaheng98.top/apps/jetty/
  - cd ./yindaheng98.top
  - git add -A
  - git commit -m 'TravisCI Deploy WebSiteAnalysisKit'
  - git push -u https://$GH_TOKEN@github.com/yindaheng98/yindaheng98.top.git HEAD:master --force
